/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.udls.grafos.vista;
import edu.udls.grafos.control.Busqueda;
import edu.udls.grafos.control.Lector;
import edu.udls.grafos.modelo.Camino;
import edu.udls.grafos.modelo.Ciudad;
import edu.udls.grafos.modelo.Grafo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaca
 */
public class Principal extends javax.swing.JFrame {
    Grafo grafo = new Grafo();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        List<Ciudad> listaCiudades = new ArrayList<>();
        List<Camino> listaCaminos = new ArrayList<>();
        
        listaCiudades = Lector.leerCiudades("C:\\Users\\Chaca\\Documents\\OneDrive - Universidad La Salle Bajío\\Semestre Dos\\Programacion Estructurada y Orientada a Objetos\\OrientadaObjetos\\Grafos\\Ciudades.txt");
        grafo.setListaCiudades(listaCiudades);
        listaCaminos = Lector.leerCaminos("C:\\Users\\Chaca\\Documents\\OneDrive - Universidad La Salle Bajío\\Semestre Dos\\Programacion Estructurada y Orientada a Objetos\\OrientadaObjetos\\Grafos\\Caminos.txt", grafo.getListaCiudades());
        grafo.setListaCaminos(listaCaminos);
        initComponents();
        txaMatriz.setText(grafo.imprimirMatriz(grafo.crearMatriz()));
        
        lblNumeroCiudades.setText(Integer.toString(grafo.getListaCiudades().size()));
        lblNumeroCaminos.setText(Integer.toString(grafo.getListaCaminos().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMatriz = new javax.swing.JTextArea();
        btnBuscarCamino = new javax.swing.JButton();
        txtCiudadOrigen = new javax.swing.JTextField();
        txtCiudadDestino = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrearCiudad = new javax.swing.JButton();
        btnCrearCamino = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        txtLatitudCiudad = new javax.swing.JTextField();
        txtLongitudCiudad = new javax.swing.JTextField();
        txtPoblacionCiudad = new javax.swing.JTextField();
        txtCaminoCiudadOrigen = new javax.swing.JTextField();
        txtCaminoCiudadDestino = new javax.swing.JTextField();
        txtCaminoDistancia = new javax.swing.JTextField();
        lblNumeroCiudades = new javax.swing.JLabel();
        lblNumeroCaminos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2), "Google", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        txaMatriz.setEditable(false);
        txaMatriz.setBackground(new java.awt.Color(255, 255, 255));
        txaMatriz.setColumns(20);
        txaMatriz.setForeground(new java.awt.Color(0, 0, 0));
        txaMatriz.setRows(5);
        jScrollPane1.setViewportView(txaMatriz);

        btnBuscarCamino.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscarCamino.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCamino.setText("Buscar Camino");
        btnBuscarCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCaminoActionPerformed(evt);
            }
        });

        txtCiudadOrigen.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudadOrigen.setForeground(new java.awt.Color(0, 0, 0));

        txtCiudadDestino.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudadDestino.setForeground(new java.awt.Color(0, 0, 0));

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ciudad de origen");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ciudad de destino");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Matriz de Grafo");

        btnCrearCiudad.setBackground(new java.awt.Color(0, 0, 255));
        btnCrearCiudad.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCiudad.setText("Crear Ciudad");
        btnCrearCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCiudadActionPerformed(evt);
            }
        });

        btnCrearCamino.setBackground(new java.awt.Color(0, 0, 255));
        btnCrearCamino.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCamino.setText("Crear Camino");
        btnCrearCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCaminoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de Ciudades");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de Caminos");

        txtNombreCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCiudad.setForeground(new java.awt.Color(0, 0, 0));

        txtLatitudCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtLatitudCiudad.setForeground(new java.awt.Color(0, 0, 0));

        txtLongitudCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtLongitudCiudad.setForeground(new java.awt.Color(0, 0, 0));

        txtPoblacionCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtPoblacionCiudad.setForeground(new java.awt.Color(0, 0, 0));

        txtCaminoCiudadOrigen.setBackground(new java.awt.Color(255, 255, 255));
        txtCaminoCiudadOrigen.setForeground(new java.awt.Color(0, 0, 0));

        txtCaminoCiudadDestino.setBackground(new java.awt.Color(255, 255, 255));
        txtCaminoCiudadDestino.setForeground(new java.awt.Color(0, 0, 0));

        txtCaminoDistancia.setBackground(new java.awt.Color(255, 255, 255));
        txtCaminoDistancia.setForeground(new java.awt.Color(0, 0, 0));

        lblNumeroCiudades.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroCiudades.setText("lblNumeroCiudades");

        lblNumeroCaminos.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroCaminos.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre de la Ciudad");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Latitud de la Ciudad");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Longitud de la Ciudad");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Poblacion de la Ciudad");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ciudad de Origen");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ciudad de Destino");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Distancia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscarCamino, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCrearCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtLatitudCiudad))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCiudadDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLongitudCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtPoblacionCiudad)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCrearCamino, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCaminoCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCaminoCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCaminoDistancia))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumeroCiudades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumeroCaminos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNumeroCiudades))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblNumeroCaminos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCamino)
                    .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCiudad)
                    .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatitudCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitudCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoblacionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCamino)
                    .addComponent(txtCaminoCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaminoCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaminoDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCaminoActionPerformed
        // TODO add your handling code here
        if(Busqueda.buscarIndiceCiudad(txtCiudadOrigen.getText(), grafo.getListaCiudades()) != -1 && Busqueda.buscarIndiceCiudad(txtCiudadDestino.getText(), grafo.getListaCiudades()) != -1){
            JOptionPane.showMessageDialog(null, "El camino entre las dos ciudades existe y su distancia es de: " + Integer.toString(grafo.buscarCamino(grafo.listaCiudades.get(Busqueda.buscarIndiceCiudad(txtCiudadOrigen.getText(), grafo.getListaCiudades())), grafo.listaCiudades.get(Busqueda.buscarIndiceCiudad(txtCiudadDestino.getText(), grafo.getListaCiudades())))));
        }else{
            JOptionPane.showMessageDialog(null, "El camino entre las dos ciudades no existe.");
        }
        txtCiudadOrigen.setText("");
        txtCiudadDestino.setText("");
    }//GEN-LAST:event_btnBuscarCaminoActionPerformed

    private void btnCrearCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCiudadActionPerformed
        // TODO add your handling code here:
        grafo.addCiudad(txtNombreCiudad.getText(), Integer.parseInt(txtLatitudCiudad.getText()), Integer.parseInt(txtLongitudCiudad.getText()), Integer.parseInt(txtPoblacionCiudad.getText()));
        txtNombreCiudad.setText("");
        txtLatitudCiudad.setText("");
        txtLongitudCiudad.setText("");
        txtPoblacionCiudad.setText("");
        JOptionPane.showMessageDialog(null, "Ciudad creada con exito.");
        
        txaMatriz.setText(grafo.imprimirMatriz(grafo.crearMatriz()));
        lblNumeroCiudades.setText(Integer.toString(grafo.getListaCiudades().size()));
    }//GEN-LAST:event_btnCrearCiudadActionPerformed

    private void btnCrearCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCaminoActionPerformed
        // TODO add your handling code here:
        if(Busqueda.buscarIndiceCiudad(txtCaminoCiudadOrigen.getText(), grafo.listaCiudades) == -1){
            JOptionPane.showMessageDialog(null, "La ciudad de origen no existe");
        }else if(Busqueda.buscarIndiceCiudad(txtCaminoCiudadDestino.getText(), grafo.listaCiudades) == -1){
            JOptionPane.showMessageDialog(null, "La ciudad de destino es inexistente");
        }else{
            grafo.addCamino(grafo.listaCiudades.get(Busqueda.buscarIndiceCiudad(txtCaminoCiudadOrigen.getText(), grafo.listaCiudades)), grafo.listaCiudades.get(Busqueda.buscarIndiceCiudad(txtCaminoCiudadDestino.getText(), grafo.listaCiudades)), Integer.parseInt(txtCaminoDistancia.getText()));
            txaMatriz.setText(grafo.imprimirMatriz(grafo.crearMatriz()));
            lblNumeroCaminos.setText(Integer.toString(grafo.getListaCaminos().size()));
            JOptionPane.showMessageDialog(null, "Camino creado con exito.");
        }
        
        txtCaminoCiudadOrigen.setText("");
        txtCaminoCiudadDestino.setText("");
        txtCaminoDistancia.setText("");
    }//GEN-LAST:event_btnCrearCaminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCamino;
    private javax.swing.JButton btnCrearCamino;
    private javax.swing.JButton btnCrearCiudad;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroCaminos;
    private javax.swing.JLabel lblNumeroCiudades;
    private javax.swing.JTextArea txaMatriz;
    private javax.swing.JTextField txtCaminoCiudadDestino;
    private javax.swing.JTextField txtCaminoCiudadOrigen;
    private javax.swing.JTextField txtCaminoDistancia;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtCiudadOrigen;
    private javax.swing.JTextField txtLatitudCiudad;
    private javax.swing.JTextField txtLongitudCiudad;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtPoblacionCiudad;
    // End of variables declaration//GEN-END:variables
}
