package com.ivanvivas.heroesapp.models

data class Hero (val publisher: Publisher, val name:String, val description:String, val image:String, val image2:String){
    companion object{
        val heroes = listOf(
            Hero(Publisher.publishers[1],"Wonder Woman","Guerrera amazona, hija de Zeus y embajadora de paz de Themyscira, defensora de la justicia con su lazo de la verdad y brazaletes indestructibles", "https://variety.com/wp-content/uploads/2023/08/Screen-Shot-2023-08-10-at-3.43.28-PM.png", "https://i.pinimg.com/originals/f4/68/f8/f468f8e87c957cff3f5e0ce43061378d.png"),
            Hero(Publisher.publishers[1],"Batman","Vigilante nocturno de Gotham, experto en artes marciales, tecnología avanzada y uno de los mejores detectives del mundo, conocido por su lucha incansable contra el crimen tras la muerte de sus padres", "https://i.guim.co.uk/img/media/c8c00617b792d1d53f2d2b318820d5758dc61551/231_0_2968_1782/master/2968.jpg?width=1200&quality=85&auto=format&fit=max&s=99459057199a54c97181e29b0947b5fb", "https://www.pngarts.com/files/2/Batman-PNG-Background-Image.png"),
            Hero(Publisher.publishers[1],"Flash","Héroe con supervelocidad, vinculado a la Fuerza de la Velocidad, capaz de viajar en el tiempo, su identidad es Barry Allen, un científico forense que usa sus poderes para salvar Central City", "https://media.revistagq.com/photos/6490312847440fcd9be41fb7/master/pass/flash.jpg", "https://i.pinimg.com/originals/83/10/59/83105916580f7b38172a68bc0cd688bb.png"),
            Hero(Publisher.publishers[1],"Superman","Último hijo de Krypton, conocido como el Hombre de Acero, símbolo de esperanza y protector de la Tierra, criado como Clark Kent en Kansas y dotado de poderes extraordinarios gracias a la energía del Sol", "https://media.newyorker.com/photos/5909527c1c7a8e33fb38a864/master/pass/Man_of_Steel-580.jpeg", "https://i.pinimg.com/originals/84/3d/3c/843d3cc2bea7c8df224e878e8b6326dd.png"),
            Hero(Publisher.publishers[1],"Aquaman","Rey de Atlantis y defensor de los océanos, con la capacidad de comunicarse telepáticamente con la vida marina y dotado de una fuerza sobrehumana, lucha por unir la superficie y el mundo submarino", "https://i.blogs.es/565887/aquaman-and-the-lost-kingdom-official-images-hi-res-11/1366_2000.jpeg", "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0f091ec3-dbfb-48b4-b63c-d4af1b16e6dd/dfg65dc-69a7ab0b-c3a5-4a79-adaf-3459a389cfde.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzBmMDkxZWMzLWRiZmItNDhiNC1iNjNjLWQ0YWYxYjE2ZTZkZFwvZGZnNjVkYy02OWE3YWIwYi1jM2E1LTRhNzktYWRhZi0zNDU5YTM4OWNmZGUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.WA-hjS95YnNGAlMmRvrt3PH_8gsTIzqKQX_hIeMmgU4"),
            Hero(Publisher.publishers[1],"Green Lantern","Portador del anillo de poder, miembro del Green Lantern Corps, su voluntad convierte sus pensamientos en constructos de luz sólida, protege el universo del mal junto a otros Lanterns", "https://media.npr.org/assets/img/2011/06/13/greenman_wide-240bf2467b6ce588886d171a5a5ddc81d07e22e0.jpg?s=1400&c=100&f=jpeg", "https://www.pngall.com/wp-content/uploads/10/Green-Lantern-PNG-Images-HD.png"),
            Hero(Publisher.publishers[1],"Shazam","Niño transformado en poderoso héroe con la magia del Mago Shazam, posee la sabiduría de Salomón, la fuerza de Hércules y el poder de Zeus, entre otras habilidades sobrehumanas", "https://discussingfilm.net/wp-content/uploads/2019/03/shazam-1.jpg", "https://i.pinimg.com/originals/9c/e6/ad/9ce6ad65be393ea1410f8f94c9412359.png"),
            Hero(Publisher.publishers[1],"Harley Quinn","Ex-psiquiatra del Asilo Arkham convertida en criminal, famosa por su relación con el Joker, aunque ha evolucionado para ser una antiheroína independiente con gran habilidad en el combate", "https://wallpapers.com/images/featured/harley-quinn-wovpo1ssyp5e92w5.jpg", "https://www.pngarts.com/files/3/Harley-Quinn-PNG-Transparent-Image.png"),
            Hero(Publisher.publishers[1],"Green Arrow","Arquero experto y multimillonario, Oliver Queen protege Star City con su arco y flechas especializadas, inspirado por su sentido de justicia después de sobrevivir en una isla desierta", "https://people.com/thmb/Ynz8BLWstg_VfQZaleLjVo-OhKg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(999x0:1001x2)/arr622b_0100b-2000-d200ac6b3b5444c4a3c4cf9413cde220.jpg", "https://artinsights.com/wp-content/uploads/2013/11/20130530115924.png"),
            Hero(Publisher.publishers[1],"Nightwing","Ex-Robin, ahora héroe independiente, Dick Grayson protege Blüdhaven, conocido por su acrobacia, habilidad en combate y liderazgo de los Jóvenes Titanes", "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/09/nightwing-mystery.jpg", "https://static.wikia.nocookie.net/dbxfanon/images/d/db/Nightwing_transparent_by_asthonx1-db13elm.png/revision/latest?cb=20181126202350"),

            Hero(Publisher.publishers[0],"Iron Man","Genio, multimillonario, filántropo y playboy, Tony Stark usa una avanzada armadura tecnológica para combatir amenazas globales como Iron Man, líder de los Vengadores", "https://wallpapers.com/images/featured/iron-man-superhero-ponky3hlfivddo2m.jpg", "https://i.pinimg.com/originals/93/1a/4d/931a4d2fc3840addcf01965ef3c2bfe3.png"),
            Hero(Publisher.publishers[0],"Thor","Dios del trueno y príncipe de Asgard, empuñador del martillo Mjolnir, protector de los Nueve Reinos y miembro de los Vengadores, con fuerza sobrehumana y control del rayo", "https://img2.rtve.es/i/?w=1600&i=1585840423850.jpg", "https://pngmaterial.com/dvsxyz02/uploads/thor-desenho-png.png"),
            Hero(Publisher.publishers[0],"Capitan America","Steve Rogers, super soldado y símbolo de la libertad, mejorado durante la Segunda Guerra Mundial, maneja su icónico escudo de vibranio con destreza y lidera los Vengadores", "https://cdn.marvel.com/content/1x/003cap_ons_cut_dsk_01_1.jpg", "https://i.pinimg.com/originals/89/39/93/893993cf74bf7bd4c2f6cf445db31e7e.png"),
            Hero(Publisher.publishers[0],"Hulk","Bruce Banner, un científico brillante transformado en el increíble Hulk, una bestia verde de fuerza ilimitada causada por la radiación gamma, con una dualidad entre su intelecto y su furia", "https://cdn.britannica.com/64/182864-050-8975B127/Scene-The-Incredible-Hulk-Louis-Leterrier.jpg", "https://www.pngarts.com/files/2/Hulk-PNG-Picture.png"),
            Hero(Publisher.publishers[0],"Spiderman","Peter Parker, joven estudiante convertido en superhéroe tras ser mordido por una araña radiactiva, con habilidades arácnidas y un sentido de responsabilidad que lo guía a proteger Nueva York", "https://wallpapers.com/images/hd/spiderman-background-oycfyb1ksermw921.jpg", "https://clipart.info/images/ccovers/1559828354spiderman-png-marvel-9.png"),
            Hero(Publisher.publishers[0],"Wolverine","Logan, también conocido como Lobezno, es un mutante con garras de adamantium, factor curativo y un pasado violento, miembro de los X-Men y héroe solitario con instintos animales", "https://cdn.marvel.com/content/1x/034wlv_com_mas_dsk_03.jpg", "https://www.pngarts.com/files/2/Wolverine-PNG-Picture.png"),
            Hero(Publisher.publishers[0],"Black Panther","T'Challa, rey de Wakanda, una nación avanzada y tecnológicamente superior, protector de su pueblo con el poder del místico Pantera Negra y habilidades sobrehumanas gracias a la hierba corazón", "https://media.newyorker.com/photos/5a87650156b75c08a3e5bbb6/16:9/w_1280,c_limit/Cobb-Black-Panther.jpg", "https://www.pngarts.com/files/9/Marvel-Black-Panther-PNG-Transparent-Images.png"),
            Hero(Publisher.publishers[0],"Doctor Strange","Stephen Strange, ex cirujano convertido en el Hechicero Supremo, maestro de las artes místicas, protegiendo la Tierra de amenazas sobrenaturales desde su Sanctum Sanctorum", "https://www.intofilm.org/intofilm-production/2520/scaledcropped/1170x658/resources/2520/doctor-strange-crop.jpg", "https://i.pinimg.com/originals/77/94/20/7794203bd3c017009454cf68786dc295.png"),
            Hero(Publisher.publishers[0],"Ant-Man","Scott Lang, ladrón reformado y el segundo en portar el traje de Ant-Man, con la capacidad de cambiar de tamaño gracias a la tecnología Pym, usa sus habilidades para luchar contra el mal y proteger a su hija", "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2018_28/2493076/180710-ant-man-se-143p.jpg", "https://i.pinimg.com/originals/0f/e0/69/0fe069eb3db63d50a3fd1abf14018e84.png"),
            Hero(Publisher.publishers[0],"Scarlet Witch","Wanda Maximoff, poderosa mutante y bruja con la capacidad de manipular la realidad y la magia del caos, una Vengadora atormentada por su pasado y su inmenso poder", "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/05/scarlet-witch-s-powers-in-the-mcu-and-marvel-comics.jpg", "https://i.pinimg.com/originals/44/41/42/4441424af49f921b47fa50bbc2f88a7a.png")
        )
    }
}