# Generated by Django 5.1.2 on 2024-11-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_alter_respuesta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.pregunta'),
        ),
    ]
