package edu.udls.proyectoblockbuster.vista;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaca
 */
public class ArchiveLocations extends javax.swing.JFrame {
    //SE DECLARAN DOS STRINGS CON PROTECCION PARA QUE SEAN ACCESADOS UNICAMENTE DESDE EL PAQUETE VISTA
    protected static String routeAvailableMovies = "";
    protected static String routeRentedMovies = "";
    
    /**
     * Creates new form ArchiveLocations
     */
    public ArchiveLocations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscadorPeliculasDisponibles = new javax.swing.JButton();
        txtAvailableMovies = new javax.swing.JTextField();
        buscadorPeliculasRentadas = new javax.swing.JButton();
        txtRentedMovies = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReady = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true), "BlockBuster", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(204, 204, 0))); // NOI18N

        buscadorPeliculasDisponibles.setBackground(new java.awt.Color(255, 255, 0));
        buscadorPeliculasDisponibles.setForeground(new java.awt.Color(0, 0, 153));
        buscadorPeliculasDisponibles.setText("Buscar");
        buscadorPeliculasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorPeliculasDisponiblesActionPerformed(evt);
            }
        });

        txtAvailableMovies.setEditable(false);
        txtAvailableMovies.setBackground(new java.awt.Color(255, 255, 255));
        txtAvailableMovies.setForeground(new java.awt.Color(0, 0, 0));

        buscadorPeliculasRentadas.setBackground(new java.awt.Color(255, 255, 0));
        buscadorPeliculasRentadas.setForeground(new java.awt.Color(0, 0, 153));
        buscadorPeliculasRentadas.setText("Buscar");
        buscadorPeliculasRentadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorPeliculasRentadasActionPerformed(evt);
            }
        });

        txtRentedMovies.setEditable(false);
        txtRentedMovies.setBackground(new java.awt.Color(255, 255, 255));
        txtRentedMovies.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Lista de peliculas rentadas");

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Lista de peliculas disponibles");

        btnReady.setBackground(new java.awt.Color(255, 255, 0));
        btnReady.setForeground(new java.awt.Color(0, 0, 153));
        btnReady.setText("Continuar");
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscadorPeliculasRentadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRentedMovies)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscadorPeliculasDisponibles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 362, Short.MAX_VALUE))
                            .addComponent(txtAvailableMovies))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReady)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorPeliculasDisponibles)
                    .addComponent(txtAvailableMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorPeliculasRentadas)
                    .addComponent(txtRentedMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReady)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorPeliculasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorPeliculasDisponiblesActionPerformed
        //SE CREA UN OBJETO DE LA CLASE JFILECHOOSER
        JFileChooser objectFileChooser = new JFileChooser();
        //SE UTILIZA LA FUNCION SHOWOPENDIALOG PARA PERMITIR AL USUARIO BUSCAR LA RUTA DEL ARCHIVO QUE DESEA ELEGIR
        objectFileChooser.showOpenDialog(null);
        //SE OBTIENE LA RUTA CON LA FUNCION GETSELECTEDFILE Y SE CONVIERTE EN STRING PARA GUARDARSE EN LA VARIABLE
        //ROUTEAVAILABLEMOVIES
        routeAvailableMovies = objectFileChooser.getSelectedFile().toString();
        //SE DECLARA EL CONTENIDO DEL CAMPO DE TEXTO CON LA RUTA, PARA MOSTRARSELA AL USUARIO
        txtAvailableMovies.setText(routeAvailableMovies);
    }//GEN-LAST:event_buscadorPeliculasDisponiblesActionPerformed

    private void buscadorPeliculasRentadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorPeliculasRentadasActionPerformed
        JFileChooser objectFileChooser2 = new JFileChooser();
        objectFileChooser2.showOpenDialog(null);
        routeRentedMovies = objectFileChooser2.getSelectedFile().toString();
        txtRentedMovies.setText(routeRentedMovies);
    }//GEN-LAST:event_buscadorPeliculasRentadasActionPerformed

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        //SE REVISA QUE HAYA CONTENIDO EN LOS CAMPOS DE TEXTO, ESTO SIGNIFICARIA QUE HAY UNA RUTA ESTABLECIDA EN EL STRING
        if(txtAvailableMovies.getText() != null && txtRentedMovies != null){
            //SE CREA UN OBJETO DE TIPO MAIN, ES DECIR UNA INTERFAZ PRINCIPAL
            Main interfazPrincipal = new Main();
            //SE UTILIZA LA FUNCION SHOW PARA MOSTRAR LA INTERFAZ DEL OBJETO QUE CREAMOS DE LA CLASE MAIN
            interfazPrincipal.show();
            //DE CIERRA LA INTERFAZ ACTUAL
            dispose();
        }
    }//GEN-LAST:event_btnReadyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchiveLocations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchiveLocations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchiveLocations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchiveLocations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchiveLocations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReady;
    protected static javax.swing.JButton buscadorPeliculasDisponibles;
    protected static javax.swing.JButton buscadorPeliculasRentadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField txtAvailableMovies;
    protected javax.swing.JTextField txtRentedMovies;
    // End of variables declaration//GEN-END:variables
}
